### ISSUE TITLE
bug: process_lib auto-update not enabled

### ISSUE THREAD

**Issue by jurij-jukic** [kinode-dao/process_lib#76]
Nick (in discord): the process_lib docs get autoupdated when we update crates.io, but for some reason we are waiting to enable the auto-update 
https://github.com/kinode-dao/process_lib/blob/main/.github/workflows/publish.yml#L37

**Comment by dr-frmr** [comment]
We can't do this because we rely on unpublished crates :(

Once Alloy is on crates.io, we can auto-publish with new releases.
